# -*- coding: utf-8 -*-
"""Copy of Training_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-uoD-bTFT6yhlcLxzq__1YVWD9QY1kZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/mobile_sales_data.csv')

print(df.shape)

df.info()

df.describe()

df.head()

df.tail()

missing = df.isna().sum().sort_values(ascending=False)

print(missing)

missing_pct = (missing / len(df) * 100).round(2)
print(missing_pct)

missing_table = pd.concat([missing, missing_pct], axis=1, keys=['missing_count','missing_pct'])
print(missing_table)

if 'Core Specification' in df.columns:
    missing_before = df['Core Specification'].isna().sum()
    df['Core Specification'] = df['Core Specification'].fillna('UNKNOWN')
    print(f"Core Specification: filled {missing_before} missing values with 'UNKNOWN'.")

if 'SSD' in df.columns:
    missing_before = df['SSD'].isna().sum()
    df['SSD'] = df['SSD'].fillna('UNKNOWN')
    print(f"SSD: filled {missing_before} missing values with 'UNKNOWN'.")

for col in ['Inward Date', 'Dispatch Date']:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

df.head()

print("Full duplicate rows:", df.duplicated().sum())
if 'Product Code' in df.columns:
    print("Duplicate Product Code:", df['Product Code'].duplicated().sum())

df['inward_year'] = df['Inward Date'].dt.year
df['inward_month'] = df['Inward Date'].dt.month
df['inward_weekday'] = df['Inward Date'].dt.day_name()

df['dispatch_year'] = df['Dispatch Date'].dt.year
df['dispatch_month'] = df['Dispatch Date'].dt.month
df['dispatch_weekday'] = df['Dispatch Date'].dt.day_name()

df['time_to_dispatch'] = (df['Dispatch Date'] - df['Inward Date']).dt.days

df.head()

df.info()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.head()

df['total_sales'] = df['price'] * df['quantity_sold']

df.head()

df['cost_price'] = df['price'] * 0.95
df['profit'] = df['price'] - df['cost_price']

df.head()

df['profit_margin'] = (df['profit'] / df['total_sales']) * 100

df.info()

df = df.drop(columns=['inward_date', 'dispatch_date'])

df.head()

df['brand'] = df['brand'].str.strip().str.title()
df['core_specification'] = df['core_specification'].str.strip().str.upper()
df.head()

df[df['price'] < 0]
df[df['quantity_sold'] < 0]

df[df['price'] == 0]
df[df['quantity_sold'] == 0]

df[['price', 'quantity_sold']].describe()

df[df['price'] > df['price'].quantile(0.75) * 2]

df[df['price'] < df['price'].quantile(0.25) / 2]

df.head()

df.info()

df.to_csv("Cleaned_Mobile_sales.csv",index=False)
print("Cleaned dataset saved")

import seaborn as sns
import matplotlib.pyplot as plt

import sqlite3
conn = sqlite3.connect(':memory:')
df.to_sql('mobile_sales', conn, index=False, if_exists='replace')

query = """
SELECT brand, SUM(total_sales) AS total_sales
FROM mobile_sales
GROUP BY brand
ORDER BY total_sales DESC
LIMIT 10;
"""
result = pd.read_sql(query, conn)
print(result)

plt.figure(figsize=(10,6))
plt.bar(result['brand'], result['total_sales'], color='#3F2A2B')
plt.title('Top 10 Brands by Total Sales')
plt.xlabel('Brand')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

query = """
SELECT region, SUM(profit) AS total_profit
FROM mobile_sales
GROUP BY region
ORDER BY total_profit DESC;
"""
result = pd.read_sql(query, conn)
print(result)

plt.pie(result['total_profit'], labels=result['region'], autopct='%1.1f%%', startangle=140)
plt.title('Profit Share by Region')
plt.show()

query = """
SELECT brand, AVG(price) AS avg_price
FROM mobile_sales
GROUP BY brand
ORDER BY avg_price DESC;
"""
result = pd.read_sql(query, conn)
print(result)

plt.figure(figsize=(10,6))
plt.barh(result['brand'], result['avg_price'], color='#65000b')
plt.title('Average Price per Brand')
plt.xlabel('Average Price')
plt.ylabel('Brand')
plt.show()

query = """
SELECT inward_month, SUM(total_sales) AS monthly_sales
FROM mobile_sales
GROUP BY inward_month
ORDER BY inward_month;
"""
result = pd.read_sql(query, conn)
print(result)

plt.plot(result['inward_month'], result['monthly_sales'], marker='o', color='green')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

query = "SELECT price FROM mobile_sales;"
result = pd.read_sql(query, conn)
print(result.head())

plt.hist(result['price'], bins=30, color='teal', edgecolor='black')
plt.title('Price Distribution')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

query = "SELECT cost_price, profit FROM mobile_sales;"
result = pd.read_sql(query, conn)
print(result.head())

plt.scatter(result['cost_price'], result['profit'], alpha=0.5, color='magenta')
plt.title('Profit vs Cost Price')
plt.xlabel('Cost Price')
plt.ylabel('Profit')
plt.show()

corr = df[['price','quantity_sold','total_sales','profit']].corr()
print(corr)

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

query = """
SELECT brand, AVG(profit_margin) AS avg_profit_margin
FROM mobile_sales
GROUP BY brand
ORDER BY avg_profit_margin DESC;
"""
result = pd.read_sql(query, conn)
print(result.head())

plt.figure(figsize=(10,6))
sns.barplot(x="brand", y="avg_profit_margin", data=result, color="#E3BC9A")
plt.title("Average Profit Margin by Brand")
plt.xlabel("Brand")
plt.ylabel("Average Profit Margin (%)")
plt.xticks(rotation=45)
plt.show()

